### ISSUE TITLE
Running scripts in background

### ISSUE THREAD

**Issue by rupakkarki27** [ruifigueira/playwright-crx#12]
Hey @ruifigueira, awesome work here and thank you for this.

I just wanted to ask a quick question. Is it possible to run our scripts in the background without visibly opening a tab in the browser and only navigate to the page once the script is complete? I have been trying to figure this out but can't seem to get anywhere.

Thanks.

**Comment by rupakkarki27** [comment]
Hey @ruifigueira, thank you for `playwright-crx`, I was wondering if you had any contribution page where we can contribute to.

**Comment by lukassvec** [comment]
Happy holidays. Took me a while to get back to this. @ruifigueira, I appreciate the work you do and how responsive you've been. Do you have means to accept monetary donations ($500) like github sponsorship, paypal, or venmo?
