### ISSUE TITLE
[Feature] Support custom testIdAttribute

### ISSUE THREAD

**Issue by Az8th** [ruifigueira/playwright-crx#15]
Hi, could you please add support for custom test ID attributes ?

Currently, it is only supported for the default one (`data-testid`), which can be used by [page.byTestId()](https://playwright.dev/docs/locators#locate-by-test-id)

Thanks

**Comment by Az8th** [comment]
Thanks a lot, especially for supporting it that quick ;)

**Comment by ruifigueira** [comment]
You're welcome. I'll release this when playwright releases 1.43.0. If you want, you can build playwright-crx and install recorder-crx extension as an [unpacked extension](https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world#load-unpacked).

Then, to configure `testIdAttribute`:

![image](https://github.com/ruifigueira/playwright-crx/assets/1374559/0aa5e80f-59af-4de5-bd45-d2c998ff2fec)
