### ISSUE TITLE
Issue recording a specific link

### ISSUE THREAD

**Issue by HarishTeens** [ruifigueira/playwright-crx#24]
Hey @ruifigueira ,
Love the amazing work you've done with the extension 🤟 

Take a look at this link: [https://lifescievents.com/event/effector/](https://lifescievents.com/event/effector/)
This page contains a "Access to Replay" button. Clicking the button spawns a form, that is loaded via an iframe.
The Extension fails to record any actions performed on that particular frame.
Seems to be a problem with dynamically loaded frames into the DOM. Do you have any thoughts on this?

P.S. This link seems to be working fine in case of the original playwright CLI record, hence created the issue here :)

**Comment by ruifigueira** [comment]
This is related with #20. Chrome 126+ now supports out-of-process iframes (the form found at that site is one). I'm trying Chrome Canary, which is a 126 version, with playwright-crx 0.6.0 which has just released and it works (with some minor issues like leaving the whole iframe highlighted while highlighting elements inside it):

https://github.com/ruifigueira/playwright-crx/assets/1374559/72eb3b61-e925-42d8-a740-d069dbec794e

**Comment by HarishTeens** [comment]
Thanks for the quick reply, I will wait until Chrome126 gets stable. Seems like there's nothing much we can do here

**Comment by ruifigueira** [comment]
I'll leave this issue open then. Let me investigate that.

**Comment by ruifigueira** [comment]
FInally I had some time to investigate. The problem is on Registration Type. If you skip that field when recording and just fill **First Name** and **Last Name**, it actually works.

I tried with codegen and it also has the same problem on Registration Type, and the reason is that the label overlaps the select field and so the select field only is editable after clicking over it (it triggers a CSS animation that moves the label up).

**Comment by HarishTeens** [comment]
Hey, Are you sure you faced issues with `playwright codegen` ? I tried it on Chrome browser now and it started working. I know it wasn't last week.
Also look at the difference between Codegen & CRX. CRX treats the entire frame as one block, while Codegen can identify the components inside it.

### CRX
![Screenshot 2024-05-16 at 1 12 07 PM](https://github.com/ruifigueira/playwright-crx/assets/33366456/8aaa1d65-544e-4e20-82eb-5a9e07867a3c)
### Codegen
![Screenshot 2024-05-16 at 1 13 22 PM](https://github.com/ruifigueira/playwright-crx/assets/33366456/8556149e-0f3f-4f67-aeb1-ef24af788051)

**Comment by HarishTeens** [comment]
Hey @ruifigueira , I tried it again it works even with selecting "Registration Type". I think the upstream has fixed it somehow.
Thanks for the help man 🤟

**Comment by HarishTeens** [comment]
Forgot to mention an important detail, for it to work. I had to click on the extension then "reload the page" again so it could detect all the DOM elements.
