### ISSUE TITLE
Chrome extension doesn't record anything after first activity

### ISSUE THREAD

**Issue by VigneshHexo** [ruifigueira/playwright-crx#29]
I installed the Chrome extension and I am trying to generate code. Unfortunately nothing gets recorded after the first activity. I also see that the page close code is generated immediately after navigation without me actually closing the page. This can be seen in the recording. I have recorded my screen here. Please let me know if I am doing something wrong: https://www.loom.com/share/5190345308c84b3ca78580dce6662fcb?sid=206db437-6e07-4c51-98b7-347cff793d1f

<img src="https://github.com/ruifigueira/playwright-crx/assets/125873180/7ba43714-6d9f-43ce-ad86-817b21ac600a" width="300" height="auto">

**Comment by ruifigueira** [comment]
The left menu in that page you are testing is a map, which is not currently supported by playwright vscode. so it's normal that it doesn't record those actions:

![image](https://github.com/ruifigueira/playwright-crx/assets/1374559/aa3bd4ce-1451-47d7-988b-ac1e7ff3131f)

However, it should record when you click another links. I noticed that at ~29sec. of the video, the **"Playwright CRX" started debugging this browser** bar disappears, and then it no longer highlights the hovered elements. Did you cancel it?

**Comment by VigneshHexo** [comment]
No. I didn't cancel it! It is still running. But somehow the page close
code appears

**Comment by VigneshHexo** [comment]
Hi Rui @ruifigueira, 
Did something interesting. I created a new chrome profile and installed the extension again. Retried to do the same thing and it worked fine. I think the issue was with one of the other Chrome extensions that I have been using or with some Chrome settings that I have. I couldn't pin point the issue. But this is good workaround at the moment :-) Thanks for excellent extension 🎉
