### ISSUE TITLE
[Question] Run playwright-crx in sidePanel

### ISSUE THREAD

**Issue by github-fw** [ruifigueira/playwright-crx#32]
Hey @ruifigueira, awesome work here and thank you for this. 
I just wanted to ask a quick question. I want to run Playwright CRX in the sidePanel, as shown in the picture below. I want it to record the switching of tab pages and the contents of clicks and run normally. I have been thinking about it for a long time and don't know how to do it. Please give me some guidance.
<img width="1918" alt="image" src="https://github.com/user-attachments/assets/c4c92ae5-0d3f-43d3-918f-11c05a3b722b">

**Comment by github-fw** [comment]
Hi @ruifigueira ，
Thank you for your answer，I feel ashamed of myself because I don't have much experience in browser plugin development, so it is difficult for me to refactor playWright. Do you have any plans to implement this feature in the future? Can you share your plans with me?

**Comment by wck821829906** [comment]
> Hi @github-fw,
> 
> Actually, that's something I had in mind to implement. Right now, changing that means changing the core code of playwright-crx, because the code that instantiates the recorder window / tab is in crxRecordApp.ts. My idea is to refactor and remove it from there and only keep a `chrome.runtime.Port`. Then, in `examples/recorder-crx`, we could create either a sidebar or a window+tab, create a communication port for it and pass it to `crxRecorderApp`.

Exciting refactoring plan. For a better user experience, I also very much hope that the playwright window can be quickly fixed in the browser sidebar through configuration, looking forward to it.

**Comment by ruifigueira** [comment]
I'll try to do it for the next release.

**Comment by ruifigueira** [comment]
Some progress on sidepanel:

https://github.com/user-attachments/assets/9718b081-2395-4a64-83de-f1749318c0f9

**Comment by github-fw** [comment]
> Some progress on sidepanel:
> 
>  2024-09-30.14-15-15.mp4

ruifigueira, you are truly an exceptional developer! Your contributions to the open-source community are admirable, and the speed and efficiency with which you handle issues are truly impressive. Thank you for your swift and excellent work; your efforts are invaluable to us.

**Comment by ruifigueira** [comment]
Thanks. BTW it is already available in https://chromewebstore.google.com/detail/playwright-crx/jambeljnbnfbkcpnoiaedcabbgmnnlcd?hl=en. A review there would be very appreciated :D
