### ISSUE TITLE
Edit Output

### ISSUE THREAD

**Issue by paul-asvb** [ruifigueira/playwright-crx#37]
Love the extension.
I would like to enable non technical people to use it.
Is there a way to edit the output? e.g. after you made a mistake.
Or am i missing something?

**Comment by ruifigueira** [comment]
Hi @paul-asvb ,

unfortunately, that's not possible right now, as I explained here: https://github.com/ruifigueira/playwright-crx/issues/35#issuecomment-2439416210 .

**Comment by paul-asvb** [comment]
Thanks for the quick anwer!
