### ISSUE TITLE
Question: How to set sources from the side-panel (or from extension interaction)

### ISSUE THREAD

**Issue by EiffelFly** [ruifigueira/playwright-crx#48]
Hi, Thanks for putting this library together, it brings many inspiration and features to what I am working on. Would you mind sharing more about, how to "setSources" from the chrome extension side. Since right now, looks like all the event is coming from the playwright using this method `playwrightSetSources`. Is it possible to set up a bi-directional channel?

Thanks again.

**Comment by ruifigueira** [comment]
Hi @EiffelFly 

do you mean setting recorded sources? I'm kind of working on that right now, as part of https://github.com/ruifigueira/playwright-crx/issues/46 . The idea is to be able to save the **Node.js > Test Runner** source and then restore the source from the javascript.

I'm implementing a way to feed that source back to the recorder. It requires a small patch to playwright, but it's mostly straightforward.

To call it, it will be something like: 

```js
  await crxApp.recorder.reset(`
      import { test, expect } from '@playwright/test';

      test('test', async ({ page }) => {
        await page.goto('https://demo.playwright.dev/todomvc/#/');
        await page.getByPlaceholder('What needs to be done?').click();
        await page.getByPlaceholder('What needs to be done?').fill('Hello, World!');
        await page.getByPlaceholder('What needs to be done?').press('Enter');
      });
    `);
  });
```

**Comment by EiffelFly** [comment]
This is amazing! I have a follow-up question

Does playwright-recorder will respect this changes?

Right now the behavior is something like 

1. Client click the window
2. Playwright record the script and convert it to source

Let's say I click three button. 

Then I programmatically trigger this function, to add one single line. 

Then I click another button on the window, does the new output sources include the line I programmatically added?

**Comment by ruifigueira** [comment]
Yes, when you load a script it will convert it into a recorderSource, and so you can add additional actions to it, or at least it's what I intend

**Comment by EiffelFly** [comment]
@ruifigueira Thanks you!!

I am very interested in this repo, if you need any help or any contribution, please let me know!

**Comment by ruifigueira** [comment]
Thanks @EiffelFly . Well, if you want to take a look on `feat/js-parser-interpreter` branch and give it a try, I already have the parser there.

In **NodeJs > Test Runner**, if not recording, it's possible to change the code and run it. Fell free to try it and give me feedback. It's still buggy, though :)

**Comment by ruifigueira** [comment]
I'm closing this issue, as it's already merged in main. Documentation is still missing, but here's an example:

```ts
await crxApp.recorder.load(`import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demo.playwright.dev/todomvc/#/');
  await page.getByPlaceholder('What needs to be done?').fill('Hello World!');
  await page.getByPlaceholder('What needs to be done?').press('Enter');
  await expect(page.getByTestId('todo-title')).toContainText('Hello World!');
  await page.getByLabel('Toggle Todo').check();
  await page.getByRole('button', { name: 'Clear completed' }).click();
});`);

Valid code is a javascript subset: only code that could be generated by the recorder, basically. BTW, it's also possible to edit the code directly in the recorder as long it's not recording. It will run the edited version also.

**Comment by EiffelFly** [comment]
Thanks @ruifigueira 🙏
