### ISSUE TITLE
Drag and Drop support

### ISSUE THREAD

**Issue by autonomobil** [ruifigueira/playwright-crx#49]
I saw your old fork https://github.com/ruifigueira/playwright/tree/feat/record-drag-drop to enable drap and drop for the playwright recorder. Any way to get that going in playwright crx as an experimental feature? 

Pretty sure it won't get to the official repo any time soon, but it would be awesome to have it in the chrome extension
- https://github.com/microsoft/playwright/issues/19892
- https://github.com/microsoft/playwright/pull/27985#issuecomment-1889725126

**Comment by ruifigueira** [comment]
Hi Moritz, I did try it back in the day. I'm not sure if it would be worth adding that without it being in playwright. I'm trying to be as minimal as possible in my patches because every time they release a new version I want to easily merge their changes.
