### ISSUE TITLE
How can I run the extension recorder with both trace and storage enabled?

### ISSUE THREAD

**Issue by h-tiwari-dev** [ruifigueira/playwright-crx#50]
Hello, 

I need some help on enabling storage to save authentication credentials for future use. Additionally, I want to activate Playwright's tracing mechanism in the extension to capture DOM screenshots for each action performed.

The goal is to create additional test cases using an LLM and Playwright scripts. The workflow involves the user recording their actions once, and then I will generate variations of those actions using the LLM. To achieve this, the first step is to store the user's authentication credentials, allowing them to be reused during interactions in my server and sending this to the LLM. The DOM screenshots from the tracer will also serve as contextual input to guide the LLM.

Even if I cannot setup trace at first. I think getting the Auth state and rerunning it with a normal playwright tracer on my server will also do for now.

**Comment by ruifigueira** [comment]
Hi,

in the current release, there's already a way to get storage state (cookies and local storage, just like in playwright). I even included an experimental feature to download it.

You can check https://github.com/ruifigueira/playwright-crx/releases/tag/v0.11.0, it explains how to activate it.

Nevertheless, I'm changing the way cookies are obtained for the next release: d83aa21368bf2c02d7b3fa1e692a2fc492290c0c

Regarding traces, you want them to be enabled while you're recording or while the script is playing?
