### ISSUE TITLE
About the newly added HMR implementation

### ISSUE THREAD

**Issue by EiffelFly** [ruifigueira/playwright-crx#57]
Hi @ruifigueira,

I just saw you implementing the HMR on the recorder-crx, The way you build the vite dev config is very interesting, thanks for providing such useful strategy.

I have a question though, when I clone the repo and operate it, I found myself ending up with a weird spot, which, when I use dev mode, the debug recording highlighter will show up, but no matter how I click here or there, the recorded codegen actions didn't show up in the recorder.

But when I use the build mode, it work naturally like before.

I would like to know whether you have experienced the same thing?

Thanks again!

**Comment by ruifigueira** [comment]
Can you try to delete `playwright/packages/playwright-core/src/generated`, run `npm run generate:pw` and try again?

**Comment by EiffelFly** [comment]
hi @ruifigueira Thanks for your reply!

I try to delete the generated folder you mentioned and run the generated script again but without luck, under dev mode it is still showing the playwright highlight red selector and when click the recorder didn't show up the codegen script. 

I am wondering how to debug this, since the services worker didn't spilt out error, and crxApplication is attached to new page

**Comment by ruifigueira** [comment]
You can debug the service worker, setting some breakpoints into `recorderCollection.ts` functions. When you are in recording mode, that class is the one that intercepts those events on the service worker side.

Nevertheless, I did try to run in a clean environment:

- I did a git clone of the project
- I ran:

```
npm ci
npm run build:crx
npm run dev
```

and it worked that way.

**Comment by EiffelFly** [comment]
@ruifigueira Thanks for your hint, I will try to debug it, I suspect that is due to some of my configuration or stuff. I will return to this issue if I find anything new 👌

**Comment by EiffelFly** [comment]
@ruifigueira I found why, somehow, the whole recorder is attached but the mode is still standby. I think I know how to resolve my problem, thank for your help!

**Comment by ruifigueira** [comment]
That's great!
