### ISSUE TITLE
[Feature] Support cookies

### ISSUE THREAD

**Issue by ruifigueira** [ruifigueira/playwright-crx#8]
Support `context.cookies()` API.

CDP [Storage.getCookies](https://vanilla.aslushnikov.com/?Storage.getCookies) is not available, but if our chrome extension has `cookies` permissions (with `host_permissions` specifying supported hosts), we can retrieve those cookies with [chrome.cookies.getAll](https://developer.chrome.com/docs/extensions/reference/cookies/#method-getAll)

**Comment by ducan-ne** [comment]
Or just reject support for `context.cookies()` api and tell user use chrome.cookies api instead

**Comment by lwintermelon** [comment]
Storage Domain is available on [chrome.debugger](https://developer.chrome.com/docs/extensions/reference/api/debugger#restricted_domains) now (what about before?),  so [Storage.getCookies](https://chromedevtools.github.io/devtools-protocol/tot/Storage/#method-getCookies) will work.

**Comment by ruifigueira** [comment]
When I first tried it, it was already documented that it supported `Storage` domain but for some reason `Storage.getCookies` was not working. But now it seems to work, so I'll try to make this work.

It will be very handy to export a playwright compatible [storageState](https://playwright.dev/docs/api/class-browsercontext#browser-context-storage-state) for attached tabs.

**Comment by ruifigueira** [comment]
Fixed in 185c296. An experimental feature to save storage state from the recorder extension will be added in the 0.11.0
